"""Initial migration

Revision ID: a9fef7e09e55
Revises: 
Create Date: 2025-03-19 19:02:22.371100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fef7e09e55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('received_time', sa.DateTime(), nullable=True),
    sa.Column('sent_time', sa.DateTime(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('receiver_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_log')
    # ### end Alembic commands ###
